---
- name: Install Distribution Packages
  apt:
    cache_valid_time: "{{pkginstall_cache_ttl}}"
    install_recommends: "{{pkginstall_recommended}}"
    name: "{{item}}"
    state: "present"
    update_cache: "{{pkginstall_update_cache}}"
  when: "ansible_distribution in ['Debian', 'Ubuntu', ]"
  with_items: "{{pkginstall_packages}}"

# TODO: (or not) make this generic for other distros
# vim: et:sw=2:syntax=yaml:ts=2:
